name: Build and update project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nodejs
        run: sudo apt install nodejs npm libxml2 libxslt python3.10

      - name: Install Typescript
        run: |
          sudo npm i -g typescript

      - name: Install Typescript
        run: |
          sudo pip3 install beautifulsoup4

      - name: Build project
        run: bash build.sh

      - name: Build web
        run: bash build_web.sh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static/
